### ISSUE TITLE
ADMIN-VIEW-EVENT-REGISTER (BACK)

### ISSUE THREAD

**Issue by baybiebxm** [SomSanTech/gatherfy-back#9]

**Comment by baybiebxm** [comment]
ที่ API: `/api/v1/registrations` (คิดว่าต้องกรองเอาแค่ registration ของอีเว้นตัวเอง)
เพราะตอนนี้มันเอา registration list ของทั้งระบบมา ความเป็นจริงน่าจะต้องเอามาแค่ registration ของอีเว้นตัวเอง 

`/v1/events/registration/{ownerId}` อันนี้ถูกแล้ว เอามาแค่อีเว้นตัวเอง
![image](https://github.com/user-attachments/assets/1dfc22d2-f2d9-4454-be7f-c8cfc065bdc3)

แต่ `/api/v1/registrations` มันเอา registration ของคนอื่นมาโชว์ด้วย คืออีเว้น THE NIGHTMARE'S TALE และ VIOLET EVERGARDEN LIVE IN CONCERT
![image](https://github.com/user-attachments/assets/993a8cd3-ed36-4300-a8f2-5ea80fae507a)

**Comment by sealbb** [comment]
> ที่ API: `/api/v1/registrations` (คิดว่าต้องกรองเอาแค่ registration ของอีเว้นตัวเอง) เพราะตอนนี้มันเอา registration list ของทั้งระบบมา ความเป็นจริงน่าจะต้องเอามาแค่ registration ของอีเว้นตัวเอง
> 
> `/v1/events/registration/{ownerId}` อันนี้ถูกแล้ว เอามาแค่อีเว้นตัวเอง ![image](https://private-user-images.githubusercontent.com/88096696/384582100-1dfc22d2-f2d9-4454-be7f-c8cfc065bdc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExODM3OTksIm5iZiI6MTczMTE4MzQ5OSwicGF0aCI6Ii84ODA5NjY5Ni8zODQ1ODIxMDAtMWRmYzIyZDItZjJkOS00NDU0LWJlN2YtYzhjZmMwNjViZGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDIwMTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYjU1NmM2MDRjNjdhMzdkNTc4ZjU3ZDk1ZTliOTk2N2YxMGYxNTMwNjI3OTFiNGUyMzMzYWMxOWY3ZGE1NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uRrnLlncZQQUcl8R9_a1G94Lz64ZuhWHFjuSl0jN5g4)
> 
> แต่ `/api/v1/registrations` มันเอา registration ของคนอื่นมาโชว์ด้วย คืออีเว้น THE NIGHTMARE'S TALE และ VIOLET EVERGARDEN LIVE IN CONCERT ![image](https://private-user-images.githubusercontent.com/88096696/384582139-993a8cd3-ed36-4300-a8f2-5ea80fae507a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExODM3OTksIm5iZiI6MTczMTE4MzQ5OSwicGF0aCI6Ii84ODA5NjY5Ni8zODQ1ODIxMzktOTkzYThjZDMtZWQzNi00MzAwLWE4ZjItNWVhODBmYWU1MDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDIwMTgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YmMyZjkyZWQ2OWZlNzk5N2ViMTFlM2RhODE4Yzc5YjExM2MwNWU5YTA1YzUyOGE1MzAwNTU4Y2EyMDMwZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zq_FBfPiNSIZaIstGdf0eZWx9OHSGflP_zhVw01KckM)

![image](https://github.com/user-attachments/assets/243fc7be-f77f-4cbc-966d-fc8109b8c446)
ที่พิมมาหมายถึงอยากได้แบบ api อันนี้มั้ยนะ เหมือนมันทำงานเหมือนกัน หรือกุเข้าใจผิด
